const test=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const context={window:{},crypto:require('node:crypto').webcrypto,structuredClone};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../agenda-model.js'),'utf8'),context);
const M=context.window.PaymentAgendaModel;
function fixture(){const m=M.emptyMonth();m.debts=[M.block('Luz',[['Importe','20000'],'Notas']),M.block('Préstamos míos',[['Banco A','50000'],['Banco B','25000']]),M.block('Movistar',[['Hogar','10000'],['Celular','15000']]),M.block('ATM',[['Importe','5000']]),M.block('Préstamos Ezequiel',[['Importe','12000']])];m.debts[0].dueDate='2026-10-15';m.debts[1].fields[0].dueDate='2026-10-20';m.debts[2].homeDueDate='2026-10-12';m.debts[2].cellDueDate='2026-10-18';m.cards=[M.block('Visa',[['Vence','22/10'],['Mío','30000']])];return m;}
test('replaces manual order with own payments and dates without changing source or total',()=>{const m=fixture(),before=JSON.stringify({debts:m.debts,cards:m.cards,total:M.ownTotal(m)});M.syncOrder(m);assert.equal(m.order.map(x=>x.label).join('|'),'Luz|Préstamos míos · Banco A|Préstamos míos · Banco B|Movistar · Hogar|Movistar · Celular|ATM|Visa');assert.equal(m.order[0].orderDate,'2026-10-15');assert.equal(m.order[3].orderDate,'2026-10-12');assert.equal(m.order[6].orderDate,'22/10');assert.equal(JSON.stringify({debts:m.debts,cards:m.cards,total:M.ownTotal(m)}),before);assert.equal(M.validMonth(m),true);});
test('sync preserves order and checks while refreshing, adding and removing sources',()=>{const m=fixture();M.syncOrder(m);const first=m.order.shift();first.paid=true;m.order.push(first);const id=first.id;m.debts[0].label='Luz actualizada';m.debts[0].dueDate='2026-10-17';M.syncOrder(m);assert.equal(m.order.at(-1).id,id);assert.equal(m.order.at(-1).paid,true);assert.equal(m.order.at(-1).label,'Luz actualizada');assert.equal(m.order.at(-1).orderDate,'2026-10-17');const before=JSON.stringify(m);M.syncOrder(m);assert.equal(JSON.stringify(m),before);m.cards=[];m.debts.push(M.block('Gas',['Importe']));M.syncOrder(m);assert.equal(m.order.some(x=>x.label==='Visa'),false);assert.equal(m.order.at(-1).label,'Gas');});
test('next month clears dates and checks while retaining chosen order',()=>{const m=fixture();M.syncOrder(m);m.order.reverse();m.order[0].paid=true;const next=M.nextMonth(m);assert.equal(next.order.map(x=>x.label).join('|'),m.order.map(x=>x.label).join('|'));assert.equal(next.order.every(x=>!x.paid&&!x.orderDate),true);assert.equal(M.validMonth(next),true);});
